# Configuración de constantes en el juego

match_room:
  max_players: 10 # cantidad máxima de jugadores

match:
  round_duration: 120 # duración máxima de la ronda en segundos
  preparation_time: 5 # tiempo para la fase de preparación o previa de la ronda (tiempo de tienda)
  max_rounds: 10 # cantidad de rondas de la partida

player:
  speed: 80 # velocidad del jugador
  money: 800 # monedas iniciales
  health: 100 # salud máxima

weapons:
  ak47:
    damage: 35 # daño por bala
    price: 2700 # precio del arma
    bullets: 30
    rate_of_fire: 24 

  awp:
    damage: 100 # daño por disparo
    price: 3500 # precio del arma
    bullets: 10
    rate_of_fire: 20 # tiempo de recarga

  glock:
    damage: 45 # daño por bala
    bullets: 40
    rate_of_fire: 700 

  knife:
    damage: 20 # daño del cuchillo

  m3:
    damage: 70 # daño por disparo
    price: 3000 # precio del arma
    bullets: 20
    rate_of_fire: 60

bomb:
  time_to_explode: 15 # tiempo hasta que explota (en segundos)

window:
  width: 800 # ancho de la ventana
  height: 600 # alto de la ventana
  fullscreen: 0 # 0 para ventana, 1 para pantalla completa

